#ifndef _ERRORCODE_H
#define _ERRORCODE_H

#define MYERROR_SUCCESS			0
#define MYERROR_INVALID_PARA	-1
#define MYERROR_NODEFINE		-2
#define MYERROR_BUFFERLACK		-3
#define MYERROR_HOSTMATCHFAIL	-4
#define MYERROR_INVALID_SNSTR	-5
#define MYERROR_INVALID_DATA	-5
#define MYERROR_INVALID_WARRANTCODE	-5
#define MYERROR_CONFLICT_UNIT_SN	-6
#define MYERROR_CONFLICT_UNIT_CODE	-6
#define MYERROR_OVERDUE_SN			-7
#define MYERROR_FALSE		-8
#define MYERROR_CONFLICT_HOST_CODE	-9

#endif